"""
ExamForge - AI Question Ingestion Agent Example
This script demonstrates how your question generator agent can push generated questions
directly into the ExamForge PostgreSQL database via the API endpoint.
"""

import requests
import json

import os

# 1. Configuration
API_BASE_URL = os.environ.get("EXAMFORGE_API_URL", "http://localhost:3000")  # Or: https://examforge-pink.vercel.app
INGEST_ENDPOINT = f"{API_BASE_URL}/api/questions/ai-ingest"
API_SECRET_KEY = os.environ.get("AI_INGEST_SECRET", "ef_ai_ingest_secret_key_placeholder")

HEADERS = {
    "Content-Type": "application/json",
    "x-api-key": API_SECRET_KEY,  # or "Authorization": f"Bearer {API_SECRET_KEY}"
}


def check_connection_and_curriculum():
    """Optional: Check endpoint status and fetch available exams/subjects/topics"""
    response = requests.get(INGEST_ENDPOINT, headers=HEADERS)
    if response.status_code == 200:
        print(" Connected to ExamForge API!")
        data = response.json()
        print(f"Available Exams: {[e['name'] for e in data.get('availableCurriculum', [])]}")
        return data
    else:
        print(f" Connection failed: {response.status_code} - {response.text}")
        return None


def push_questions_to_db(questions_payload):
    """
    Push questions generated by the AI agent into the database.
    
    The payload can be:
    - A batch of questions under an exam/subject/topic
    - An individual question
    - Or an array of questions
    """
    response = requests.post(
        INGEST_ENDPOINT,
        headers=HEADERS,
        data=json.dumps(questions_payload)
    )
    
    if response.status_code == 201:
        result = response.json()
        print(f" Successfully stored {result.get('storedCount')} questions in the database!")
        for item in result.get('savedQuestions', []):
            print(f"  - [{item['id']}] {item['exam']} > {item['subject']} > {item['topic']}: {item['questionText'][:50]}...")
        return result
    else:
        print(f" Failed to push questions: {response.status_code}")
        print(response.json())
        return None


if __name__ == "__main__":
    # Step 1: Health check
    check_connection_and_curriculum()

    # Step 2: Sample batch generated by your AI agent
    sample_agent_output = {
        "examCode": "RRB",                                     # Exam code or name (auto-created if not exists)
        "subjectName": "General Science",                      # Subject name (auto-created if not exists)
        "topicName": "Biology",                                # Topic name (auto-created if not exists)
        "bundleName": "RRB General Science Practice Set 1",    # Target bundle (auto-created & linked directly!)
        "bundlePrice": 49,                                     # Optional price in INR
        "questions": [
            {
                "questionText": "Which organelle is known as the powerhouse of the cell?",
                "optionA": "Nucleus",
                "optionB": "Ribosome",
                "optionC": "Mitochondria",
                "optionD": "Endoplasmic Reticulum",
                "correctAnswer": "C",            # Must be A, B, C, or D
                "explanation": "Mitochondria are responsible for cellular respiration and ATP generation.",
                "difficulty": "Easy",            # Easy, Medium, or Hard
                "tags": "biology, cell, rrb"     # Optional: comma-separated string or array
            },
            {
                "questionText": "What is the normal human body temperature in Celsius?",
                "optionA": "35°C",
                "optionB": "37°C",
                "optionC": "39°C",
                "optionD": "41°C",
                "correctAnswer": "B",
                "explanation": "Normal human body temperature is approximately 37°C (98.6°F).",
                "difficulty": "Easy",
                "tags": "human body, biology"
            }
        ]
    }

    # Step 3: Push to database
    push_questions_to_db(sample_agent_output)
